apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http-nginx
              containerPort: 80
        - name: network-multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - name: http-multitool
              containerPort: 8080
