apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http-nginx
      port: 9001
      targetPort: 80
    - name: http-multitool
      port: 9002
      targetPort: 8080
