---
vector_url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
vector_version: 0.21.1
nginx_user_name: root
vector_config:
  sources:
      our_log:
        ignore_older_secs: 600
        include:
          - /var/log/nginx/access.log
        read_from: beginning
        type: file
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - our_log
      database: logs
      endpoint: http://{{ hostvars['clickhouse-01'].ansible_default_ipv4.address }}:8123
      table: access_logs
      compression: gzip
      healthcheck: false
      skip_unknown_fields: true