---
- name: test
  gather_facts: false
  hosts: all
  vars:
    ansible_ssh_user: ubuntu
  become: yes
  tasks:
    - name: Install Nginx Web Server on Debian Family
      apt:
        name: nginx
        state: latest
        update_cache: yes