---
all:
  hosts:
    sonar-01:
      ansible_host: 84.201.133.98
      ansible_user: qwerty
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
    nexus-01:
      ansible_host: 158.160.46.255
      ansible_user: qwerty
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <someuser>
