---
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install_NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start-nginx

- name: LIGHTHOUSE | Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: LIGHTHOUSE | Install unzip
  become: true
  ansible.builtin.yum:
    name: unzip
    state: present
    update_cache: true
- name: LIGHTHOUSE | Get lighthouse distrib
  ansible.builtin.get_url:
    url: "{{ lighthouse_vcs }}/archive/refs/heads/master.zip"
    dest: "./lighthouse.zip"
    mode: "0644"
- name: LIGHTHOUSE | Unarchive lighthouse distrib into nginx
  become: true
  ansible.builtin.unarchive:
    src: ./lighthouse.zip
    dest: "{{ lighthouse_location_dir }}"
    remote_src: true
  notify: Reload-nginx
- name: LIGHTHOUSE | Create general config
  become: true
  ansible.builtin.template:
    src: templates/config_lighthouse.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload-nginx