apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http-nginx
              containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /usr/share/nginx/html

        - name: network-multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HTTP_PORT
          ports:
            - name: http-multitool
              containerPort: 8080
      volumes:
        - name: nginx-config-volume
          configMap:
            name: configmap-nginx-config
