---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 84.252.131.153
      # ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
    jenkins-agent-01:
      ansible_host: 158.160.49.53
      # ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
            jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: qwerty
