apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "rc1a-liblk79hyadcw9l7.mdb.yandexcloud.net"
            - name: PMA_USER
              value: "netology"
            - name: PMA_PASSWORD
              value: "qwerty123"
