apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http-multitool
      protocol: TCP
      port: 1180
      targetPort: 11800
  type: ClusterIP
