all:
  hosts:
    node1:
      ansible_host: 10.128.0.3
      ip: 10.128.0.3
      access_ip: 10.128.0.3
    node2:
      ansible_host: 10.128.0.35
      ip: 10.128.0.35
      access_ip: 10.128.0.35
    node3:
      ansible_host: 10.128.0.19
      ip: 10.128.0.19
      access_ip: 10.128.0.19
    node4:
      ansible_host: 10.128.0.16
      ip: 10.128.0.16
      access_ip: 10.128.0.16
    node5:
      ansible_host: 10.128.0.38
      ip: 10.128.0.38
      access_ip: 10.128.0.38
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
