---
- name: Install clickhouse
  hosts: clickhouse-01
  roles: 
    - clickhouse

- name: Install lighthouse
  hosts: lighthouse-01
  roles: 
    - lighthouse-role

- name: Install vector
  hosts: vector-01
  roles:
    - vector-role